# IskoLinux: a telepítő (Calamares) alapértelmezett helyszíne Budapest, így az időzóna és a
# számok, dátumok formátuma is magyar lesz. A Debian csomag nem ad saját locale.conf-ot.
---
region: "Europe"
zone: "Budapest"
localeGenPath: "/etc/locale.gen"
